
server:
  port: 8802

spring:
  application:
    name: service-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9901/eureka/
      
feign:
  hystrix:
    enabled: true